import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :user_http_registration_service, UserHttpRegistrationServiceWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4001],
  check_origin: false,
  code_reloader: true,
  debug_errors: false,
  render_errors: [view: UserHttpRegistrationServiceWeb.ErrorView, accepts: ~w(json)],
  secret_key_base: "Majb2twlC+F61MFhgKnWeUHpBcOEQ/gm0croPhTqYFONK9A69V8wabf2PCw5g6/h",
  watchers: []

config :user_http_registration_service,
  remote_password_controller_node: :password_controller@localhost,
  remote_user_controller_node: :user_controller@localhost,
  remote_password_controller_super: {PasswordController.TaskSupervisor, :password_controller@localhost},
  remote_user_controller_super: {UserController.TaskSupervisor, :user_controller@localhost},
  remote_password_controller_module: PasswordController,
  remote_user_controller_module: UserController

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
