import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :http_user_entry_point_service, HttpUserEntryPointServiceWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: false,
  render_errors: [view: HttpUserEntryPointServiceWeb.ErrorView, accepts: ~w(json)],
  secret_key_base: "fYfvId/N+7MdqnMaxrNlYhyX7EanhgAkQCyfYxVghOwuA/Bg2zMgDOTX4BbMdB9a",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :task_adapters_for_user_service, :service_users,
  remote_node: :service_users@localhost,
  remote_supervisor: {Controller, :service_users@localhost},
  remote_module: Controller


config :task_adapters_for_confirming_email_service, :service_confirming_email,
  remote_node: :service_confirming_email@localhost,
  remote_supervisor: {Controller, :service_confirming_email@localhost},
  remote_module: Controller

config :task_adapters_for_notifying_service, :service_notifying,
  remote_node: :service_notifying@localhost,
  remote_supervisor: {Controller, :service_notifying@localhost},
  remote_module: Controller


config :task_adapters_for_user_jwt_service, :service_jwt,
  remote_node: :service_jwt@localhost,
  remote_supervisor: {Controller, :service_jwt@localhost},
  remote_module: Controller,
  secret_key: "dhriklbnciesc84uiv71",
  secret_ex_key: "ap098hvb3w3dh8mvg754"
